// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSYAwAxE2nq2BSVh0aqXqIv8gaZPoD4aE',
    appId: '1:230202888134:web:37e63498f38478d330ecc7',
    messagingSenderId: '230202888134',
    projectId: 'cvault-d4348',
    authDomain: 'cvault-d4348.firebaseapp.com',
    storageBucket: 'cvault-d4348.appspot.com',
    measurementId: 'G-VB9K60D94R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6e3APkYG3hYG4XpCyW4UuQux0R1tKHtk',
    appId: '1:230202888134:android:b76e964a9e3b9b3030ecc7',
    messagingSenderId: '230202888134',
    projectId: 'cvault-d4348',
    storageBucket: 'cvault-d4348.appspot.com',
  );

}